[phases.setup]
nixPkgs = ["nginx"]

[phases.build]
cmds = ["echo 'Building static site...'"]

[phases.install]
cmds = ["echo 'No install needed for static site'"]

[start]
cmd = "nginx -g 'daemon off;'"
